# adapted from 'Using semantic-release with GitHub Actions'
# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md

name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies via CI
        run: npm ci
      - name: Lint codebase
        run: npm run lint
      - name: Test codebase
        run: npm test
      - name: Load secrets from 1Password
        id: op-credentials
        uses: 1password/load-secrets-action@main
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          # Human-readable 1Password CLI secret reference - 'op://SA - Repos_GitHub/dr-scripts/DR_SCRIPTS_NPM_TOKEN'
          DR_SCRIPTS_NPM_TOKEN: 'op://yhyrnlsxmxerazmg3j2rvjxzpq/ij2h5yoaamvzlbqx7pnxbwrdj4/DR_SCRIPTS_NPM_TOKEN'
      - name: Release package
        env:
          # Note that environment secret key names for semantic-release must be GITHUB_TOKEN and NPM_TOKEN.
          # https://github.com/semantic-release/github/blob/master/README.md
          # https://github.com/semantic-release/npm/blob/master/README.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ steps.op-credentials.outputs.DR_SCRIPTS_NPM_TOKEN }}
        run: npx semantic-release --branches main
